### PR TITLE
Fixes addon for ember 2.1

### LINKED ISSUE #2: Uncaught TypeError: container.optionsForType is not a function
I installed and ran the generator. Now when running the app, I get:

`Uncaught TypeError: container.optionsForType is not a function` in /initializers/setup-sanitizers.js.

This is in an Ember 2.1.0 project. I have successfully used this addon with a 1.13.x project.

### PR DESCRIPTION
**Pull request by mjuniper**
This fixes the addon for ember 2.1. However it surely breaks it for earlier versions. Not sure how you want to handle that. Perhaps separate releases?

Closes #2

### CODE REVIEW

**Comment by mjuniper** [comment]
- Upgraded the project to ember-cli 1.13.8 and ember/ember-data 2.1.0.
- Tests should pass now

**Comment by rlivsey** [comment]
I think it's ok to require 2.x onwards now, anyone stuck on 1.x can pin to the current version.

I'll release this as 0.1.0 shortly.

Thanks!

**Comment by fsmanuel** [comment]
@rlivsey can you release 0.1.0?

**Comment by rlivsey** [comment]
Published v1.0, seemed a good a time as any!

@fsmanuel thanks for the prod - had slipped my mind.

**Comment by fsmanuel** [comment]
@rlivsey :+1:

**Pull request merged**
